Updating Bor Bor, making it math nerd
Aurorastation/BOREALISbot2 pull request #29
Opened 2019-05-15 22:07 UTC by Sindorman

This PR does these things:

- Adds new command `pick` which picks between random choice between n number of choices separated by commas.

- Adds new command `math` which use all of python in-built math functions and `math` library functions too. Uses python syntax as input

- Adds new command `math_functions` which gives list of all functions it can run and examples of how to use `math`

- Adds `requirements-install.bat` script that is used to install requirements automatically, given that user has Python 3.6+ installed with pip3.

- memes command now displays skull and dagger emojies if user types `!memes skull`

2019-05-15 22:25 UTC, skull132 requested changes
Move the maths stuff into its own cog. (Either a maths cog, or a more generic utilities cog.) Remove the globals and global init -> move it into the new cog's init function.

2019-05-15 22:25 UTC, skull132 commented on cogs/silly.py
> +safe_dict = dict()
```suggestion
safe_dict = {}
```

(This is faster, believe it or not.)

2019-05-15 22:25 UTC, skull132 commented on cogs/silly.py
> +        await ctx.send("```List of all math functions:\n{}\n\nUse them like {}(number or function)\nEach function needs brackets\nOr you can use operators like (2 + 5 / 4) ^ 2```".format(clean, rand_
f-string this.

2019-05-15 22:25 UTC, skull132 commented on cogs/silly.py
> +        """Does math. Uses python syntax with math library. Use like \"math 5 + 3\" or \"math [function](5)\". To get list of all functions use math_functions command."""
Are these escaped quotes needed?

2019-05-24 21:44 UTC, Sindorman commented
Issues addressed

2019-05-25 11:38 UTC, skull132 approved these changes

2019-05-25 11:38 UTC, skull132 commented on cogs/math.py
> +            await ctx.send(f"You need to give some numbers and functions to me")
```suggestion
            await ctx.send("You need to give some numbers and functions to me")
```
not an f-string.

2019-05-30 20:08 UTC, skull132 requested changes
Snake case for var and method names please and thank you. PascalCase for class names is fine.

2019-05-30 20:08 UTC, skull132 commented on cogs/math.py
> +    def pushFirst(self, strg, loc, toks):
Please use snake_case for function names.

2019-05-30 20:08 UTC, skull132 commented on cogs/math.py
> +    def pushUMinus(self, strg, loc, toks):
Please use snake_case for function names.

2019-05-30 20:08 UTC, skull132 commented on cogs/math.py
> +    def evaluateStack(self, s):
snake_case

2019-05-30 20:08 UTC, skull132 commented on cogs/math.py
> +        if op in "+-*/^%":
```suggestion
        elif op in "+-*/^%":
```

2019-05-30 20:08 UTC, skull132 commented on cogs/math.py
> +    def eval(self, num_string, parseAll=True):
```suggestion
    def eval(self, num_string, parse_all=True):
```

2019-05-30 20:08 UTC, skull132 commented on cogs/math.py
> +        self.exprStack = []
```suggestion
        self.expr_stack = []
```

2019-07-18 17:07 UTC, skull132 approved these changes

2019-07-18 17:08 UTC, merged